name: mobile_witelon_bank
description: A mobile banking application for Witelon University.
publish_to: 'none' # Remove this line if you intend to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Upewnij się, że to pasuje do Twojej wersji Flutter SDK

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 # Domyślna paczka dla ikon iOS

  # Zarządzanie stanem
  provider: ^6.1.2 # Lub najnowsza stabilna wersja

  # Komunikacja HTTP z API
  http: ^1.2.1 # Lub najnowsza stabilna wersja

  # Bezpieczne przechowywanie danych (np. tokenu JWT)
  flutter_secure_storage: ^9.0.0 # Lub najnowsza stabilna wersja

  # Formatowanie dat, liczb, walut itp.
  intl: ^0.19.0 # Lub najnowsza stabilna wersja

  # Uzyskiwanie dostępu do popularnych lokalizacji w systemie plików
  path_provider: ^2.1.3 # Lub najnowsza stabilna wersja

  # Zarządzanie uprawnieniami aplikacji
  permission_handler: ^11.3.1 # Lub najnowsza stabilna wersja

  file_saver: ^0.2.9
  # open_file_plus: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Lub najnowsza wersja

flutter:
  uses-material-design: true

  # Aby dodać zasoby (assets) do aplikacji, dodaj sekcję assets, np.:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #   - assets/images/bank_logo.png # Jeśli dodasz logo

  # Aby dodać niestandardowe czcionki:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700