name: mobile_witelon_bank
description: A mobile banking application for Witelon University.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0' # Upewnij się, że to pasuje do Twojej wersji Flutter SDK

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2 # Lub nowsza wersja
  http: ^1.2.1 # Lub nowsza wersja
  flutter_secure_storage: ^9.0.0 # Lub nowsza wersja
  intl: ^0.19.0 # LUB NAJNOWSZA WERSJA Z PUB.DEV (dla formatowania daty/liczb)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Lub najnowsza wersja

flutter:
  uses-material-design: true
  # assets:
  #   - assets/images/bank_logo.png